# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 661354d8719c2761c510451d47dd4dfcbc37c8f7f7086a5dac4240dc3979d4c7136242b8b309a14e531d8331732a55a9a55971cd07363c32cc73fea40b242543

test:
  secret_key_base: c814eb5c63a01ed114f4d4844e20ab686be2fde4229faec80da13757978eac201cfa8bd1772dd63e8d29a79e2ac319df8939bdde959422855bfb12e392970977

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
